localCustomFormatsPath: /config/custom_formats
telemetry: true
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false
# ======================================================================
# RADARR
# ======================================================================
radarr:
  ##########################################    Movies   ##########################################
  movies:
    base_url: !secret RADARR_URL
    api_key: !secret RADARR_API_KEY
    quality_profiles:
      - name: HD
        language: Original
        reset_unmatched_scores:
          enabled: false
        upgrade:
          allowed: true
          until_quality: FULLHD
          until_score: 25500
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: FULLHD
            qualities:
              - Bluray-2160p
              - WEBDL-2160p
              - WEBRip-2160p
              - Bluray-1080p
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HD
            qualities:
              - Bluray-720p
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV
            qualities:
              - HDTV-2160p
              - HDTV-1080p
              - HDTV-720p
          - name: SD
            qualities:
              - Bluray-576p
              - WEBDL-480p
              - WEBRip-480p
              - DVD
              - SDTV
    