apiVersion: v1
kind: Secret
metadata:
  name: configarr
  namespace: arr
type: Opaque
stringData:
  secrets_yml: |
    SONARR_URL: "http://sonarr.arr.svc.cluster.local:8989"
    RADARR_URL: "http://radarr.arr.svc.cluster.local:7878"
    SONARR_ANIMES_URL: "http://sonarr-animes.arr.svc.cluster.local:8990"
    RADARR_ANIMES_URL: "http://radarr-animes.arr.svc.cluster.local:7879"
    
    SONARR_API_KEY: "sua-api-key-aqui"
    RADARR_API_KEY: "sua-api-key-aqui"
    SONARR_ANIMES_API_KEY: "sua-api-key-animes-aqui"
    RADARR_ANIMES_API_KEY: "sua-api-key-animes-aqui"