apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: SEU_NAMESPACE
resources:
  - configarr-config.yaml
  - configarr-cronjob.yaml
  - configarr-pvc.yaml
  - configarr-secrets.yaml
